version: '3.8'

services:
  postgres:
    build:
      context: ./bdd-postgre
    container_name: plm_postgres
    env_file:
      - .env
    volumes:
      - ./bdd-postgre/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql:ro
      - ./bdd-postgre/data:/data

  backend:
    build:
      context: ./backend
    container_name: plm_backend
    env_file:
      - .env
    volumes: #Pour éviter de devoir rebuild les images à chaque changement sur les fichiers
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: plm_frontend
    volumes: #Pour éviter de devoir rebuild les images à chaque changement sur les fichiers
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:80"